[features]
seeds = false
[programs.localnet]
social_blocks = "55VX31JFN1H5UAxHTbpWE2xEMoJSm8DznJorY8S4mkAp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/grinch/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
